- platform: workday
  country: US

- platform: ping
  name: Internet Connection
  host: google.com
  count: 2

- platform: template
  sensors:
    trash_day:
      friendly_name: "Trash Day"
      value_template: >-
        {{ is_state('sensor.day_of_the_week', 'Wednesday') }} 

- platform: template
  sensors:
    phone_presence:
      friendly_name: "Phone Presence"
      device_class: presence
      value_template: >-
        {{ states.sensor.bluetooth_presence_probability.state | int > 50 or is_state('device_tracker.iphone', 'home') }}
    car_presence:
      friendly_name: "Car Presence"
      device_class: presence
      value_template: >-
        {{ is_state('binary_sensor.garage_car_present', 'on') or is_state('binary_sensor.jeep_presence', 'on') or is_state('device_tracker.car_gps', 'home') }}
    homekit_presence:
      friendly_name: "HomeKit Presence"
      device_class: presence
      value_template: >-
        {{ is_state('input_boolean.homekit_presence', 'on') }}
    motion_presence:
      friendly_name: "Motion Presence"
      device_class: presence
      value_template: >-
        {{ is_state('group.motion_sensors', 'on') }}
      delay_off:
        minutes: 2
    presence:
      friendly_name: "Presence Status"
      device_class: presence
      value_template: >-
        {{ is_state('binary_sensor.bayesian_presence', 'on') }} 

- platform: bayesian
  prior: 0.15
  name: Bayesian Presence
  device_class: presence
  probability_threshold: 0.50
  observations:
    - entity_id: 'binary_sensor.phone_presence'
      prob_given_true: 0.6
      prob_given_false: 0.05
      platform: 'state'
      to_state: 'on'
    - entity_id: 'binary_sensor.homekit_presence'
      prob_given_true: 0.25
      prob_given_false: 0.05
      platform: 'state'
      to_state: 'on'
    - entity_id: 'binary_sensor.car_presence'
      prob_given_true: 0.25
      prob_given_false: 0.05
      platform: 'state'
      to_state: 'on'