esphomeyaml:
  name: bedroom_multisensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  hostname: bedroom-multisensor

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_password

logger:

ota:

sensor:
  - platform: dht
    model: DHT22
    pin: D7
    temperature:
      name: "Bedroom Temperature"
      unit_of_measurement: "°F"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
    humidity:
      name: "Bedroom Humidity"
  - platform: adc
    pin: A0
    name: "Bedroom Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: >-
          return (x / 10000.0) * 2000000.0;

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Bedroom Motion"
    device_class: motion
  - platform: status
    name: "Bedroom Multisensor Status"
