esphomeyaml:
  name: garage_car_presence
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  hostname: garage_car_presence

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_password

logger:

ota:

binary_sensor:
  - platform: status
    name: "Garage Presence Sensor Status"
  - platform: template
    name: "Garage Car Present"
    device_class: presence
    filters:
      - heartbeat: 20min
    on_press: 
      then: 
        - light.turn_on:
            id: status_led
            red: 0%
            green: 100%
            blue: 0%
    on_release: 
      then: 
        - light.turn_on:
            id: status_led
            red: 100%
            green: 0%
            blue: 0%
    lambda: >-
      if (isnan(id(ultrasonic_garage).value)) {
        // NAN means the echo timed out, so return unknown.
        return {};
      } else if (id(ultrasonic_garage).value < 1) {
        // car present
        return true;
      } else {
        // no car
        return false;
      }

sensor:
  - platform: ultrasonic
    id: ultrasonic_garage
    trigger_pin: D5
    echo_pin: D6
    name: "Garage Ultrasonic"
    timeout_time: 10s
    expire_after: 5min
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5

output:
  - platform: esp8266_pwm
    pin: D2
    id: redgpio
  - platform: esp8266_pwm
    pin: D3
    id: greengpio
  - platform: esp8266_pwm
    pin: D4
    id: bluegpio

light:
  - platform: rgb
    id: status_led
    discovery: false
    internal: true
    name: "Status Light"
    red: redgpio
    green: greengpio
    blue: bluegpio