- alias: 'Entry Lights On'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: 'on'
      to: 'off'
  condition:
    - condition: time
      after: '16:00'
  action: 
    - service: light.turn_on
      entity_id: light.entry_lights_level

- alias: 'Return from Away'
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: 'on'
      to: 'off'
  action: 
    - service: homeassistant.turn_on
      entity_id: automation.welcome_motion
    - service: light.turn_on
      entity_id: group.switchplate_backlights
    - service: nest.set_away_mode
      data:
        away_mode: home

- alias: 'Disarm Cameras'
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: 'on'
      to: 'off'
  action: 
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.aarlo_jq_arlo

- alias: 'Disarm Alarm'
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      to: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.alarm_controller_disarm
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.alarm_com
        code: !secret adc_code

- alias: "Close To Home Disarm"
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      value_template: '{{ states.proximity.home.state | float }}'
      below: 1000
  condition: 
    - condition: template
      value_template: '{{ states.proximity.home.attributes.dir_of_travel == "towards" }}'
  action:
    - service: switch.turn_on
      entity_id: switch.alarm_controller_disarm
    - service: nest.set_away_mode
      data:
        away_mode: home

- alias: 'Welcome Motion'
  initial_state: False
  trigger:
    - platform: state
      entity_id: binary_sensor.stairs_motion_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.entry_motion_sensor
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.welcome_motion
    - service: scene.turn_on
      entity_id: scene.main_lights_on
    - delay:
        seconds: 4
    - service: script.welcome_greeting
    - delay:
        seconds: 10
    - service: switch.flux_update
      entity_id: switch.flux