- alias: 'Minimote Button 1 Press'
  hide_entity: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.minimote
      scene_id: 1
  action:
    - service: scene.turn_on
      entity_id: scene.main_lights_on

- alias: 'Minimote Button 2 Press'
  hide_entity: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.minimote
      scene_id: 3
  action:
    - service: scene.turn_on
      entity_id: scene.main_lights_dimmed

- alias: 'Minimote Button 3 Press'
  hide_entity: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.minimote
      scene_id: 5
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off

- alias: 'Minimote Button 4 Held'
  hide_entity: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.minimote
      scene_id: 8
  action:
    - service: script.bedtime