- alias: 'House Too Cold'
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: climate.living_room_nest
      value_template: '{{ state.attributes.current_temperature }}'
      below: 60
  action: 
    - service: script.notify
      data:
        message: "House is too cold. Temperature is {{ states.climate.living_room_nest.attributes.current_temperature }}"

- alias: 'Low Battery Alert'
  trigger:
    - platform: time
      at: '20:00'
  condition:
    - condition: template
      value_template: >-
        {% for entity_id in states.group.battery_levels.attributes.entity_id if states(entity_id) | int < 25 %}
        {%- if loop.first -%}
        {{ true }}
        {%- endif -%}
        {% endfor %}
  action:
    service: script.notify
    data:
      message: "Low battery detected for at least one sensor"

- alias: 'New Device'
  hide_entity: True
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    service: script.notify
    data_template:
      message: "New device detected: {{trigger.event.data.host_name}}"

- alias: 'Internet Failure'
  trigger:
    - platform: state
      entity_id: binary_sensor.internet_connection
      to: 'off'
  action: 
    - service: script.notify
      data:
        message: "Internet connection is DOWN"

- alias: 'Internet Restored'
  trigger:
    - platform: state
      entity_id: binary_sensor.internet_connection
      to: 'on'
  action: 
    - service: script.notify
      data:
        message: "Internet connection is restored"

- alias: 'RAM Usage Warning'
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.ram_use
      above: 96
  action: 
    - service: script.notify
      data:
        message: "RAM usage too high. Utilization is {{ states.sensor.ram_use.state }}%"

- alias: 'Startup Notification'
  hide_entity: True
  trigger:
    platform: homeassistant
    event: start
  action: 
    - service: script.notify
      data:
        message: "HASS startup complete"
    - service: frontend.set_theme
      data:
        name: slate

- alias: 'Update Available'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: script.notify
    data:
      message: 'Home Assistant update is available.'