esphome:
  name: car_approaching_sensor
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  fast_connect: true

mqtt:
  broker: !secret mqtt_host
  reboot_timeout: 0s

logger:

binary_sensor:
  - platform: status
    name: "Car Approaching"
    device_class: presence