group:
  water_leak_sensors:
    name: Water Leak Sensors
    control: hidden
    entities:
      - binary_sensor.downstairs_bathroom_water_leak
      - binary_sensor.garage_water_leak

binary_sensor:
  - platform: mqtt
    name: "Downstairs Bathroom Water Leak"
    device_class: moisture
    state_topic: "tasmota/rf_bridge/RESULT"
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret water_leak_1_code
    availability_topic: "tasmota/rf_bridge/LWT"
    payload_available:  "Online"
    payload_not_available: "Offline"
    off_delay: 60
    qos: 1

  - platform: mqtt
    name: "Garage Water Leak"
    device_class: moisture
    state_topic: "tasmota/rf_bridge/RESULT"
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret water_leak_2_code
    availability_topic: "tasmota/rf_bridge/LWT"
    payload_available:  "Online"
    payload_not_available: "Offline"
    off_delay: 60
    qos: 1

automation:
  - alias: 'Water Leak Notification'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.downstairs_bathroom_water_leak
        to: 'on'
      - platform: state
        entity_id: binary_sensor.garage_water_leak
        to: 'on'
    action:
      service: notify.push
      data_template:
        message: "Water Leak Detected! [{{ trigger.from_state.name }}]"
